# Generated by Django 5.1.1 on 2024-10-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_favorite_unique_together_favorite_restaurantid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='place_name',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
